<a href="https://colab.research.google.com/github/KhushiChaudhary-cyber/python_programs/blob/main/dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
path='/content/student_report_500.xlsx'
df=pd.read_excel(path)

In [ ]:
#to display full data
print(df)

    Student_ID        Full_Name  Gender  Class Section        City  Maths  \
0     STD-1001  Priya Choudhary    Male     10       A  Chandigarh     45
1     STD-1002      Aarav Verma    Male      7       C     Kolkata     89
2     STD-1003         Sai Iyer    Male      8       C     Kolkata     48
3     STD-1004     Ananya Singh  Female      8       C     Kolkata     84
4     STD-1005  Shreya Kulkarni    Male      8       C  Chandigarh     71
..         ...              ...     ...    ...     ...         ...    ...
495   STD-1496     Ritika Gupta    Male      7       A       Patna     69
496   STD-1497       Rohan Iyer    Male      6       B     Kolkata     85
497   STD-1498       Meera Iyer    Male      9       A     Lucknow     98
498   STD-1499       Kavya Iyer  Female     10       A     Kolkata     84
499   STD-1500  Priya Choudhary  Female      7       A       Delhi     66

     Science  English  Hindi  Social_Studies  Total  Percentage  Attendance  \
0         97       58     76              71    347        69.4          84
1         83       96     54              57    379        75.8          89
2         53       61     57              81    300        60.0          86
3         56       72     92              68    372        74.4          84
4         48       54     79              92    344        68.8          80
..       ...      ...    ...             ...    ...         ...         ...
495       80       96     76              50    371        74.2          92
496       98       49     86              48    366        73.2          79
497       83       64     96              61    402        80.4          74
498       76       62     60              64    346        69.2          64
499       54       81     44              61    306        61.2          71

    Status
0     Pass
1     Pass
2     Pass
3     Pass
4     Pass
..     ...
495   Pass
496   Pass
497   Pass
498   Pass
499   Pass

[500 rows x 15 columns]

In [4]:
df.head(10)

,Student_ID,Full_Name,Gender,Class,Section,City,Maths,Science,English,Hindi,Social_Studies,Total,Percentage,Attendance,Status
0,STD-1001,Priya Choudhary,Male,10,A,Chandigarh,45,97,58,76,71,347,69.4,84,Pass
1,STD-1002,Aarav Verma,Male,7,C,Kolkata,89,83,96,54,57,379,75.8,89,Pass
2,STD-1003,Sai Iyer,Male,8,C,Kolkata,48,53,61,57,81,300,60.0,86,Pass
3,STD-1004,Ananya Singh,Female,8,C,Kolkata,84,56,72,92,68,372,74.4,84,Pass
4,STD-1005,Shreya Kulkarni,Male,8,C,Chandigarh,71,48,54,79,92,344,68.8,80,Pass
5,STD-1006,Aarav Kulkarni,Female,7,C,Delhi,97,44,81,69,57,348,69.6,66,Pass
6,STD-1007,Meera Gupta,Male,9,C,Lucknow,93,100,58,46,67,364,72.8,74,Pass
7,STD-1008,Kavya Gupta,Male,7,C,Bhopal,63,99,44,51,59,316,63.2,66,Pass
8,STD-1009,Vivaan Verma,Male,9,B,Kolkata,81,62,65,47,57,312,62.4,73,Pass
9,STD-1010,Ananya Banerjee,Female,10,A,Kolkata,74,63,66,60,90,353,70.6,88,Pass

In [5]:
# to print last five elements
df.tail(5)

,Student_ID,Full_Name,Gender,Class,Section,City,Maths,Science,English,Hindi,Social_Studies,Total,Percentage,Attendance,Status
495,STD-1496,Ritika Gupta,Male,7,A,Patna,69,80,96,76,50,371,74.2,92,Pass
496,STD-1497,Rohan Iyer,Male,6,B,Kolkata,85,98,49,86,48,366,73.2,79,Pass
497,STD-1498,Meera Iyer,Male,9,A,Lucknow,98,83,64,96,61,402,80.4,74,Pass
498,STD-1499,Kavya Iyer,Female,10,A,Kolkata,84,76,62,60,64,346,69.2,64,Pass
499,STD-1500,Priya Choudhary,Female,7,A,Delhi,66,54,81,44,61,306,61.2,71,Pass

In [6]:
#to display random 10 records
df.sample(10)

,Student_ID,Full_Name,Gender,Class,Section,City,Maths,Science,English,Hindi,Social_Studies,Total,Percentage,Attendance,Status
361,STD-1362,Ritika Choudhary,Female,10,B,Lucknow,61,69,65,46,41,282,56.4,73,Pass
196,STD-1197,Rahul Jain,Female,7,B,Bhopal,73,98,57,85,79,392,78.4,77,Pass
458,STD-1459,Pooja Kulkarni,Female,6,B,Patna,85,52,48,54,52,291,58.2,66,Pass
62,STD-1063,Karan Sharma,Female,7,C,Patna,76,91,71,71,80,389,77.8,64,Pass
75,STD-1076,Sneha Verma,Female,6,C,Bhopal,62,40,94,91,55,342,68.4,64,Pass
248,STD-1249,Rahul Iyer,Male,6,C,Lucknow,70,76,67,64,50,327,65.4,72,Pass
482,STD-1483,Pooja Yadav,Male,6,A,Mumbai,84,71,99,57,92,403,80.6,64,Pass
492,STD-1493,Simran Das,Male,10,B,Mumbai,53,56,55,46,52,262,52.4,70,Pass
2,STD-1003,Sai Iyer,Male,8,C,Kolkata,48,53,61,57,81,300,60.0,86,Pass
152,STD-1153,Neha Kaur,Female,8,A,Kolkata,92,81,54,46,62,335,67.0,72,Pass

In [7]:
#to summarise the record
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Student_ID      500 non-null    object
 1   Full_Name       500 non-null    object
 2   Gender          500 non-null    object
 3   Class           500 non-null    int64
 4   Section         500 non-null    object
 5   City            500 non-null    object
 6   Maths           500 non-null    int64
 7   Science         500 non-null    int64
 8   English         500 non-null    int64
 9   Hindi           500 non-null    int64
 10  Social_Studies  500 non-null    int64
 11  Total           500 non-null    int64
 12  Percentage      500 non-null    float64
 13  Attendance      500 non-null    int64
 14  Status          500 non-null    object
dtypes: float64(1), int64(8), object(6)
memory usage: 58.7+ KB

In [8]:
#to display statistical summary
df.describe()

,Class,Maths,Science,English,Hindi,Social_Studies,Total,Percentage,Attendance
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,8.022000,69.852000,70.110000,69.734000,69.168000,69.474000,348.338000,69.667600,80.568000
std,1.434445,17.883336,17.563908,17.520765,17.290857,17.326562,37.500671,7.500134,11.964769
min,6.000000,40.000000,40.000000,40.000000,40.000000,40.000000,232.000000,46.400000,60.000000
25%,7.000000,54.000000,55.000000,54.000000,54.000000,54.000000,324.000000,64.800000,70.750000
50%,8.000000,71.000000,70.000000,70.000000,69.000000,68.500000,348.000000,69.600000,82.000000
75%,9.000000,85.000000,85.000000,84.000000,83.000000,85.000000,376.000000,75.200000,91.000000
max,10.000000,100.000000,100.000000,100.000000,100.000000,100.000000,437.000000,87.400000,100.000000

In [10]:
#to display name of columns
df.columns

Index(['Student_ID', 'Full_Name', 'Gender', 'Class', 'Section', 'City',
       'Maths', 'Science', 'English', 'Hindi', 'Social_Studies', 'Total',
       'Percentage', 'Attendance', 'Status'],
      dtype='object')

In [12]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
495    False
496    False
497    False
498    False
499    False
Length: 500, dtype: bool